# Generated by Django 5.0.3 on 2024-03-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Classical_Song',
        ),
    ]
